# Generated by Django 6.0 on 2025-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feedback_workprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Unavailable', 'Unavailable')], max_length=20)),
                ('profile_image', models.URLField(blank=True)),
            ],
        ),
    ]
