# Generated by Django 6.0 on 2025-12-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_servicer'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicer',
            name='available_time',
            field=models.CharField(default='9:00 AM - 6:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='servicer',
            name='email',
            field=models.EmailField(default='9:00 AM - 6:00 PM', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicer',
            name='phone',
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicer',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='servicer',
            name='work_type',
            field=models.CharField(max_length=200),
        ),
    ]
