# Generated by Django 6.0 on 2025-12-13 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_servicer_available_time_servicer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('work_type', models.CharField(max_length=100)),
                ('preferred_date', models.DateField()),
                ('complaints', models.TextField()),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.servicer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
