# Generated by Django 6.0 on 2025-12-14 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workprogress',
            old_name='work_type',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='workprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='workprogress',
            name='booking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='accounts.booking'),
            preserve_default=False,
        ),
    ]
