# Generated by Django 6.0 on 2025-12-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_address_user_city_user_pincode_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_time',
            field=models.CharField(blank=True, default='9:00 AM - 6:00 PM', help_text='Available working hours', max_length=100, null=True, verbose_name='available time'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Service center location', max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_types',
            field=models.CharField(blank=True, help_text='Types of work the servicer can do (comma-separated)', max_length=200, null=True, verbose_name='work types'),
        ),
    ]
