# Generated by Django 6.0 on 2025-12-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_available_time_user_location_user_work_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completion_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_choice',
            field=models.CharField(blank=True, choices=[('pickup', 'Servicer will pickup'), ('user_brings', 'User will bring vehicle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the service request', null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='estimated_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='work_items',
            field=models.TextField(blank=True, help_text='Comma-separated list of work items', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Requested', 'Service Requested'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
