# Generated by Django 6.0 on 2025-12-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_booking_completion_notes_booking_final_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Paid', 'Paid')], help_text='Payment status: Pending or Paid', max_length=20, null=True),
        ),
    ]
