# Generated by Django 6.0 on 2025-12-15 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_booking_payment_date_booking_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='booking',
            field=models.OneToOneField(blank=True, help_text='One feedback per booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='accounts.booking'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='servicer',
            field=models.ForeignKey(blank=True, help_text='Servicer who completed the service', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='accounts.servicer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='Feedback message'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
