# Generated by Django 6.0 on 2025-12-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_feedback_options_feedback_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_background_image', models.ImageField(blank=True, help_text='Background image for User interface', null=True, upload_to='system/user_backgrounds/')),
                ('servicer_background_image', models.ImageField(blank=True, help_text='Background image for Servicer interface', null=True, upload_to='system/servicer_backgrounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
